name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-html-demo:latest

  deploy:
    needs: build
    runs-on: [self-hosted, vm-local]
    steps:
      - name: Pull and Run Docker Container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/docker-html-demo:latest
          docker stop docker-html-demo || true
          docker rm docker-html-demo || true
          docker run -d --name docker-html-demo -p 80:80 ${{ secrets.DOCKER_USERNAME }}/docker-html-demo:latest
